modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/SkolkovoLab/ZoomSensitivityFix/issues"
license = "All Rights Reserved"

[[mods]]
modId = "zoomsensitivityfix"
version = "${version}"
displayName = "ZoomSensitivityFix"
authors = "ru.hld"
description = ""
logoFile = "assets/zoomsensitivityfix/icon.png"

[[dependencies.zoomsensitivityfix]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zoomsensitivityfix]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "zoomsensitivityfix.mixins.json"
